# Dataset Expansion

This notebook expands the original Kaggle Samsung smartphone dataset by incorporating the latest Samsung smartphones launched in 2024 and 2025.

The expanded dataset introduces additional machine learning-friendly features while preserving the original dataset.

Output:
- SamsungPhoneData_Updated.csv

In [1]:
import pandas as pd

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
df = pd.read_csv("../data/interim/SamsungPhoneData_Updated.csv")

print("Merged Dataset Shape:", df.shape)

Merged Dataset Shape: (749, 21)

In [3]:
df.head()

,Name,Dimensions,SoC,CPU,GPU,RAM,Storage,Display,Battery,OS,...,Launch_Year,Series,Main_Camera_MP,UltraWide_MP,Telephoto_MP,Front_Camera_MP,OIS,AI_Features,Waterproof,Target_Segment
0,Ativ Odyssey,59 x 110.1 x 12.3 mm,Samsung Exynos 4 Quad 4412,"2x 1.5 GHz Krait,",Broadcom VideoCore IV,"1 GB, 400 MHz",8 GB,"4 in, Super AMOLED, 480 x 800 pixels, 24 bit","2100 mAh, Li-Ion",Android 4.1.2 Jelly Bean,...,NaN,Other,8,NaN,NaN,NaN,No,No,No,Budget
1,Ativ S,63.1 x 121.5 x 10.5 mm,Qualcomm Snapdragon S1 (MSM7225A),"2x 1.5 GHz Krait,","Qualcomm Adreno 225, 400 MHz","768 MB, 333 MHz",4 GB,"4.8 in, Super AMOLED, 720 x 1280 pixels, 24 bit","2300 mAh, Li-Ion",Android 4.0.4 Ice Cream Sandwich,...,NaN,Other,3,NaN,NaN,NaN,No,No,No,Budget
2,ATIV S Neo,61.3 x 124.6 x 8.94 mm,Qualcomm Snapdragon S2 (MSM8655),"2x 1.4 GHz Krait 300,",ARM Mali-400 MP4,"1.5 GB, 400 MHz",8 GB,"4.77 in, TFT, 720 x 1280 pixels, 24 bit","2000 mAh, Li-Ion",Android 4.2.2 Jelly Bean,...,NaN,Other,8,NaN,NaN,NaN,No,No,No,Budget
3,Ativ SE,186.9 x 107.9 x 9 mm,Qualcomm Snapdragon 400 (MSM8226),"4x 2.26 GHz Krait 400,","Qualcomm Adreno 305, 450 MHz","2 GB, 800 MHz",16 GB,"5 in, AMOLED, 1080 x 1920 pixels, 24 bit","2600 mAh, Li-Ion",Microsoft Windows Phone 8,...,NaN,Other,3,NaN,NaN,NaN,No,No,No,Budget
4,Ativ Tab,63.5 x 121.9 x 12.7 mm,Qualcomm Snapdragon S4 Plus (MSM8960),"2x 1.5 GHz Krait,","Qualcomm Adreno 200, 245 MHz",1 GB,"8 GB, 16 GB","10.1 in, PLS, 1366 x 768 pixels, 24 bit","8200 mAh, Li-Ion",Android 4.0 Ice Cream Sandwich,...,NaN,Galaxy Tab Series,8,NaN,NaN,NaN,No,No,No,Budget

In [4]:
df.tail(30)

,Name,Dimensions,SoC,CPU,GPU,RAM,Storage,Display,Battery,OS,...,Launch_Year,Series,Main_Camera_MP,UltraWide_MP,Telephoto_MP,Front_Camera_MP,OIS,AI_Features,Waterproof,Target_Segment
719,Z4,73.4 x 159.5 x 8.1 mm,Spreadtrum SC9830A,"4x 1.5 GHz ARM Cortex-A7,","ARM Mali-400 MP2, 512 MHz","1 GB, 533 MHz",8 GB,"4.5 in, TFT, 480 x 800 pixels, 18 bit","2050 mAh, Li-Ion",Tizen 3.0,...,NaN,Other,13,NaN,NaN,NaN,No,No,No,Budget
720,Galaxy A15 5G,NaN,MediaTek Dimensity 6100+,Octa-core,NaN,8 GB,256 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy A Series,50,5.0,NaN,13.0,No,No,No,Budget
721,Galaxy A16 5G,NaN,MediaTek Dimensity 6300,Octa-core,NaN,8 GB,256 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy A Series,50,5.0,NaN,13.0,No,No,No,Budget
722,Galaxy A25 5G,NaN,Exynos 1280,Octa-core,NaN,8 GB,256 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy A Series,50,8.0,NaN,13.0,Yes,No,No,Budget
723,Galaxy A26 5G,NaN,Exynos 1330,Octa-core,NaN,8 GB,256 GB,NaN,5000 mAh,Android 15,...,2025.0,Galaxy A Series,50,8.0,NaN,13.0,Yes,Basic AI,Yes,Budget
724,Galaxy A35 5G,NaN,Exynos 1380,Octa-core,NaN,8 GB,256 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy A Series,50,8.0,NaN,13.0,Yes,Basic AI,Yes,Budget
725,Galaxy A36 5G,NaN,Snapdragon 6 Gen 3,Octa-core,NaN,8 GB,256 GB,NaN,5000 mAh,Android 15,...,2025.0,Galaxy A Series,50,12.0,NaN,16.0,Yes,Basic AI,Yes,Budget
726,Galaxy A55 5G,NaN,Exynos 1480,Octa-core,NaN,12 GB,256 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy A Series,50,12.0,NaN,32.0,Yes,Basic AI,Yes,Photography
727,Galaxy A56 5G,NaN,Exynos 1580,Octa-core,NaN,12 GB,256 GB,NaN,5000 mAh,Android 15,...,2025.0,Galaxy A Series,50,12.0,NaN,32.0,Yes,Galaxy AI,Yes,Photography
728,Galaxy M15 5G,NaN,MediaTek Dimensity 6100+,Octa-core,NaN,8 GB,256 GB,NaN,6000 mAh,Android 14,...,2024.0,Galaxy M Series,50,5.0,NaN,13.0,No,No,No,Budget
729,Galaxy M35 5G,NaN,Exynos 1380,Octa-core,NaN,8 GB,256 GB,NaN,6000 mAh,Android 14,...,2024.0,Galaxy M Series,50,8.0,NaN,13.0,Yes,No,No,Budget
730,Galaxy M36 5G,NaN,Exynos 1480,Octa-core,NaN,8 GB,256 GB,NaN,6000 mAh,Android 15,...,2025.0,Galaxy M Series,50,8.0,NaN,16.0,Yes,Basic AI,No,Budget
731,Galaxy M56 5G,NaN,Exynos 1580,Octa-core,NaN,12 GB,256 GB,NaN,6000 mAh,Android 15,...,2025.0,Galaxy M Series,50,12.0,NaN,32.0,Yes,Basic AI,No,Photography
732,Galaxy F15 5G,NaN,MediaTek Dimensity 6100+,Octa-core,NaN,8 GB,256 GB,NaN,6000 mAh,Android 14,...,2024.0,Galaxy F Series,50,5.0,NaN,13.0,No,No,No,Budget
733,Galaxy F35 5G,NaN,Exynos 1380,Octa-core,NaN,8 GB,256 GB,NaN,6000 mAh,Android 14,...,2024.0,Galaxy F Series,50,8.0,NaN,13.0,Yes,No,No,Budget
734,Galaxy F55 5G,NaN,Snapdragon 7 Gen 1,Octa-core,NaN,12 GB,256 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy F Series,50,8.0,NaN,50.0,Yes,No,No,Photography
735,Galaxy F56 5G,NaN,Snapdragon 7s Gen 2,Octa-core,NaN,12 GB,256 GB,NaN,5000 mAh,Android 15,...,2025.0,Galaxy F Series,50,8.0,NaN,50.0,Yes,Basic AI,No,Photography
736,Galaxy S24 FE,NaN,Exynos 2400e,Deca-core,NaN,8 GB,256 GB,NaN,4700 mAh,Android 14,...,2024.0,Galaxy S Series,50,12.0,8.0,10.0,Yes,Galaxy AI,Yes,Flagship
737,Galaxy S24,NaN,Snapdragon 8 Gen 3 / Exynos 2400,Octa-core / Deca-core,NaN,8 GB,256 GB,NaN,4000 mAh,Android 14,...,2024.0,Galaxy S Series,50,12.0,10.0,12.0,Yes,Galaxy AI,Yes,Flagship
738,Galaxy S24+,NaN,Snapdragon 8 Gen 3 / Exynos 2400,Octa-core / Deca-core,NaN,12 GB,256 GB,NaN,4900 mAh,Android 14,...,2024.0,Galaxy S Series,50,12.0,10.0,12.0,Yes,Galaxy AI,Yes,Flagship
739,Galaxy S24 Ultra,NaN,Snapdragon 8 Gen 3 for Galaxy,Octa-core,NaN,12 GB,512 GB,NaN,5000 mAh,Android 14,...,2024.0,Galaxy S Series,200,12.0,50.0,12.0,Yes,Galaxy AI,Yes,Flagship
740,Galaxy S25,NaN,Snapdragon 8 Elite,Octa-core,NaN,12 GB,256 GB,NaN,4000 mAh,Android 15,...,2025.0,Galaxy S Series,50,12.0,10.0,12.0,Yes,Galaxy AI,Yes,Flagship
741,Galaxy S25+,NaN,Snapdragon 8 Elite,Octa-core,NaN,12 GB,256 GB,NaN,4900 mAh,Android 15,...,2025.0,Galaxy S Series,50,12.0,10.0,12.0,Yes,Galaxy AI,Yes,Flagship
742,Galaxy S25 Edge,NaN,Snapdragon 8 Elite,Octa-core,NaN,12 GB,256 GB,NaN,4900 mAh,Android 15,...,2025.0,Galaxy S Series,50,12.0,10.0,12.0,Yes,Galaxy AI,Yes,Flagship
743,Galaxy S25 Ultra,NaN,Snapdragon 8 Elite for Galaxy,Octa-core,NaN,16 GB,512 GB,NaN,5000 mAh,Android 15,...,2025.0,Galaxy S Series,200,50.0,50.0,12.0,Yes,Galaxy AI,Yes,Flagship
744,Galaxy Z Flip6,NaN,Snapdragon 8 Gen 3 for Galaxy,Octa-core,NaN,12 GB,256 GB,NaN,4000 mAh,Android 14,...,2024.0,Galaxy Z Series,50,12.0,NaN,10.0,Yes,Galaxy AI,Yes,Flagship
745,Galaxy Z Fold6,NaN,Snapdragon 8 Gen 3 for Galaxy,Octa-core,NaN,12 GB,512 GB,NaN,4400 mAh,Android 14,...,2024.0,Galaxy Z Series,50,12.0,10.0,10.0,Yes,Galaxy AI,Yes,Flagship
746,Galaxy XCover7,NaN,MediaTek Dimensity 6100+,Octa-core,NaN,6 GB,128 GB,NaN,4050 mAh,Android 14,...,2024.0,Galaxy XCover Series,50,NaN,NaN,5.0,No,No,Yes,Rugged
747,Galaxy XCover7 Pro,NaN,Snapdragon 7s Gen 2,Octa-core,NaN,8 GB,256 GB,NaN,5050 mAh,Android 14,...,2024.0,Galaxy XCover Series,50,8.0,NaN,13.0,Yes,No,Yes,Rugged
748,Galaxy XCover8 Pro,NaN,Snapdragon 7 Gen 3,Octa-core,NaN,8 GB,256 GB,NaN,5050 mAh,Android 15,...,2025.0,Galaxy XCover Series,50,8.0,NaN,13.0,Yes,Basic AI,Yes,Rugged

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 749 entries, 0 to 748
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             749 non-null    str
 1   Dimensions       720 non-null    str
 2   SoC              749 non-null    str
 3   CPU              749 non-null    str
 4   GPU              720 non-null    str
 5   RAM              749 non-null    str
 6   Storage          749 non-null    str
 7   Display          720 non-null    str
 8   Battery          749 non-null    str
 9   OS               749 non-null    str
 10  Camera           720 non-null    str
 11  Launch_Year      29 non-null     float64
 12  Series           749 non-null    str
 13  Main_Camera_MP   749 non-null    int64
 14  UltraWide_MP     28 non-null     float64
 15  Telephoto_MP     9 non-null      float64
 16  Front_Camera_MP  29 non-null     float64
 17  OIS              749 non-null    str
 18  AI_Features      749 non-null    str
 19  Waterproof       749 non-null    str
 20  Target_Segment   749 non-null    str
dtypes: float64(4), int64(1), str(16)
memory usage: 123.0 KB

In [6]:
df.isnull().sum()

Name                 0
Dimensions          29
SoC                  0
CPU                  0
GPU                 29
RAM                  0
Storage              0
Display             29
Battery              0
OS                   0
Camera              29
Launch_Year        720
Series               0
Main_Camera_MP       0
UltraWide_MP       721
Telephoto_MP       740
Front_Camera_MP    720
OIS                  0
AI_Features          0
Waterproof           0
Target_Segment       0
dtype: int64

In [7]:
print("Merged Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

Merged Dataset Shape: (749, 21)

Missing Values:
Name                 0
Dimensions          29
SoC                  0
CPU                  0
GPU                 29
RAM                  0
Storage              0
Display             29
Battery              0
OS                   0
Camera              29
Launch_Year        720
Series               0
Main_Camera_MP       0
UltraWide_MP       721
Telephoto_MP       740
Front_Camera_MP    720
OIS                  0
AI_Features          0
Waterproof           0
Target_Segment       0
dtype: int64

### Observations

- The merged dataset contains both the original Kaggle records and the latest Samsung devices.
- New structured features have been added.
- Missing values are expected due to differences in schema between the original and appended datasets.
- Missing values will be handled systematically in the Data Cleaning stage.

In [8]:
df.duplicated().sum()

np.int64(0)