# Data Cleaning

## Objective

The objective of this notebook is to clean and standardize the merged Samsung smartphone dataset before Exploratory Data Analysis (EDA).

The cleaning process includes:

- Missing value analysis
- Duplicate detection
- Data type conversion
- Text standardization
- Feature extraction
- Final validation

Output:

data/processed/cleaned_dataset.csv

In [1]:
import pandas as pd
import numpy as np
import re

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../data/interim/SamsungPhoneData_Updated.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
print("Shape :", df.shape)

df.head()

Shape : (749, 21)

,Name,Dimensions,SoC,CPU,GPU,RAM,Storage,Display,Battery,OS,Camera,Launch_Year,Series,Main_Camera_MP,UltraWide_MP,Telephoto_MP,Front_Camera_MP,OIS,AI_Features,Waterproof,Target_Segment
0,Ativ Odyssey,59 x 110.1 x 12.3 mm,Samsung Exynos 4 Quad 4412,"2x 1.5 GHz Krait,",Broadcom VideoCore IV,"1 GB, 400 MHz",8 GB,"4 in, Super AMOLED, 480 x 800 pixels, 24 bit","2100 mAh, Li-Ion",Android 4.1.2 Jelly Bean,"3264 x 2448 pixels, 1920 x 1080 pixels, 30 fps",NaN,Other,8,NaN,NaN,NaN,No,No,No,Budget
1,Ativ S,63.1 x 121.5 x 10.5 mm,Qualcomm Snapdragon S1 (MSM7225A),"2x 1.5 GHz Krait,","Qualcomm Adreno 225, 400 MHz","768 MB, 333 MHz",4 GB,"4.8 in, Super AMOLED, 720 x 1280 pixels, 24 bit","2300 mAh, Li-Ion",Android 4.0.4 Ice Cream Sandwich,"2048 x 1536 pixels, 1920 x 1080 pixels, 30 fps",NaN,Other,3,NaN,NaN,NaN,No,No,No,Budget
2,ATIV S Neo,61.3 x 124.6 x 8.94 mm,Qualcomm Snapdragon S2 (MSM8655),"2x 1.4 GHz Krait 300,",ARM Mali-400 MP4,"1.5 GB, 400 MHz",8 GB,"4.77 in, TFT, 720 x 1280 pixels, 24 bit","2000 mAh, Li-Ion",Android 4.2.2 Jelly Bean,"3264 x 2448 pixels, 1920 x 1080 pixels, 30 fps",NaN,Other,8,NaN,NaN,NaN,No,No,No,Budget
3,Ativ SE,186.9 x 107.9 x 9 mm,Qualcomm Snapdragon 400 (MSM8226),"4x 2.26 GHz Krait 400,","Qualcomm Adreno 305, 450 MHz","2 GB, 800 MHz",16 GB,"5 in, AMOLED, 1080 x 1920 pixels, 24 bit","2600 mAh, Li-Ion",Microsoft Windows Phone 8,"2048 x 1536 pixels, 1280 x 720 pixels, 30 fps",NaN,Other,3,NaN,NaN,NaN,No,No,No,Budget
4,Ativ Tab,63.5 x 121.9 x 12.7 mm,Qualcomm Snapdragon S4 Plus (MSM8960),"2x 1.5 GHz Krait,","Qualcomm Adreno 200, 245 MHz",1 GB,"8 GB, 16 GB","10.1 in, PLS, 1366 x 768 pixels, 24 bit","8200 mAh, Li-Ion",Android 4.0 Ice Cream Sandwich,"3264 x 2448 pixels, 1920 x 1080 pixels, 30 fps",NaN,Galaxy Tab Series,8,NaN,NaN,NaN,No,No,No,Budget

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 749 entries, 0 to 748
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             749 non-null    str
 1   Dimensions       720 non-null    str
 2   SoC              749 non-null    str
 3   CPU              749 non-null    str
 4   GPU              720 non-null    str
 5   RAM              749 non-null    str
 6   Storage          749 non-null    str
 7   Display          720 non-null    str
 8   Battery          749 non-null    str
 9   OS               749 non-null    str
 10  Camera           720 non-null    str
 11  Launch_Year      29 non-null     float64
 12  Series           749 non-null    str
 13  Main_Camera_MP   749 non-null    int64
 14  UltraWide_MP     28 non-null     float64
 15  Telephoto_MP     9 non-null      float64
 16  Front_Camera_MP  29 non-null     float64
 17  OIS              749 non-null    str
 18  AI_Features      749 non-null    str
 19  Waterproof       749 non-null    str
 20  Target_Segment   749 non-null    str
dtypes: float64(4), int64(1), str(16)
memory usage: 123.0 KB

In [5]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing.sort_values(
    by="Missing Values",
    ascending=False
)

                 Missing Values  Percentage
Telephoto_MP                740   98.798398
UltraWide_MP                721   96.261682
Launch_Year                 720   96.128171
Front_Camera_MP             720   96.128171
Dimensions                   29    3.871829
Camera                       29    3.871829
Display                      29    3.871829
GPU                          29    3.871829
Name                          0    0.000000
CPU                           0    0.000000
SoC                           0    0.000000
Battery                       0    0.000000
RAM                           0    0.000000
Series                        0    0.000000
OS                            0    0.000000
Storage                       0    0.000000
Main_Camera_MP                0    0.000000
OIS                           0    0.000000
AI_Features                   0    0.000000
Waterproof                    0    0.000000
Target_Segment                0    0.000000

In [6]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [7]:
df.dtypes

Name                   str
Dimensions             str
SoC                    str
CPU                    str
GPU                    str
RAM                    str
Storage                str
Display                str
Battery                str
OS                     str
Camera                 str
Launch_Year        float64
Series                 str
Main_Camera_MP       int64
UltraWide_MP       float64
Telephoto_MP       float64
Front_Camera_MP    float64
OIS                    str
AI_Features            str
Waterproof             str
Target_Segment         str
dtype: object

In [8]:
yes_no_columns = [
    "OIS",
    "Waterproof"
]

for col in yes_no_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.title()
    )

In [9]:
df["AI_Features"] = (
    df["AI_Features"]
    .astype(str)
    .str.strip()
    .replace({
        "None":"No",
        "Nan":"No"
    })
)

In [10]:
camera_columns = [
    "UltraWide_MP",
    "Telephoto_MP"
]

df[camera_columns] = (
    df[camera_columns]
    .fillna(0)
)

In [11]:
df.isnull().sum()

Name                 0
Dimensions          29
SoC                  0
CPU                  0
GPU                 29
RAM                  0
Storage              0
Display             29
Battery              0
OS                   0
Camera              29
Launch_Year        720
Series               0
Main_Camera_MP       0
UltraWide_MP         0
Telephoto_MP         0
Front_Camera_MP    720
OIS                  0
AI_Features          0
Waterproof           0
Target_Segment       0
dtype: int64

In [12]:
# Save cleaned dataset
df.to_csv(
    "../data/processed/cleaned_dataset.csv",
    index=False
)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!